VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
    .string "Won't you admire my PIKACHU's\n"
    .string "adorable tail?$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
    .string "Humph!\p"
    .string "My PIKACHU is twice as cute as\n"
    .string "that one!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
    .string "I just adore my SEEL!\n"
    .string "It's so lovable!\p"
    .string "It squeals, “Kyuuuh,” when I\n"
    .string "hug it!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
    .string "Oh, dear!\p"
    .string "My SEEL is far more attractive.\n"
    .string "By double, I would say.$"

VermilionCity_PokemonFanClub_Text_Pikachu::
    .string "PIKACHU: Chu! Pikachu!$"

VermilionCity_PokemonFanClub_Text_Seel::
    .string "SEEL: Kyuoo!$"

VermilionCity_PokemonFanClub_Text_Poliwrath::
    .string "POLIWRATH: Poli!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .string "I chair the POKéMON Fan Club!\p"
    .string "I raise more than a hundred\n"
    .string "POKéMON!\p"
    .string "I'm very fussy when it comes to\n"
    .string "POKéMON! I surely am!\p"
    .string "So…\p"
    .string "Did you come visit to hear about\n"
    .string "my POKéMON?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .string "Good!\n"
    .string "Then listen up!\p"
    .string "My favorite RAPIDASH…\p"
    .string "It's…cute…lovely…smart… \n"
    .string "plus…amazing…you think so?…\l"
    .string "oh yes…it's…stunning…\l"
    .string "kindly…love it!\p"
    .string "Hug it…when…sleeping…warm\n"
    .string "and cuddly…spectacular…\l"
    .string "ravishing…\l"
    .string "…Oops! Look at the time!\l"
    .string "I kept you too long!\p"
    .string "Thanks for hearing me out!\n"
    .string "I want you to have this!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
    .string "{PLAYER} received a BIKE VOUCHER\n"
    .string "from the CHAIRMAN.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .string "Take that BIKE VOUCHER to the\n"
    .string "BIKE SHOP in CERULEAN CITY.\p"
    .string "Exchange that for a BICYCLE\n"
    .string "free of charge!\p"
    .string "Don't worry, my favorite FEAROW\n"
    .string "will FLY me anywhere I need to go.\p"
    .string "So, I have no need for a BICYCLE.\p"
    .string "I hope you like cycling!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .string "Oh. Come back when you want to\n"
    .string "hear my story!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .string "Hello, {PLAYER}!\p"
    .string "Did you come see me about my\n"
    .string "POKéMON again?\p"
    .string "No?\n"
    .string "Too bad!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .string "Make room for this!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
    .string "Our CHAIRMAN is very vocal about\n"
    .string "POKéMON.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
    .string "Let's all listen politely to other\n"
    .string "TRAINERS!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
    .string "If someone brags, brag right back!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
    .string "Our CHAIRMAN really does adore his\n"
    .string "POKéMON.\p"
    .string "But the person who is most liked by\n"
    .string "POKéMON is DAISY, I think.$"

VermillionCity_PokemonFanClub_Text_LetMeTakeLookAtMons::
    .string "You travel all over the place,\n"
    .string "don't you?\p"
    .string "May this old sailor check how\n"
    .string "you treat your POKéMON?\p"
    .string "Let me take a look.\n"
    .string "… … …   … … …$"

VermillionCity_PokemonFanClub_Text_HmmISeeIsee::
    .string "Ah, hmm…\n"
    .string "I see, I see…$"

VermillionCity_PokemonFanClub_Text_TreatMonRightHaveThis::
    .string "Oh, impressive.\n"
    .string "You treat your POKéMON with love.\p"
    .string "I think you can be entrusted with\n"
    .string "this.\p"
    .string "Please, I'd like you to have this.$"

VermillionCity_PokemonFanClub_Text_ReceivedEggFromMan::
    .string "{PLAYER} received an EGG\n"
    .string "from the man!$"

VermillionCity_PokemonFanClub_Text_DontHaveSpaceInYourParty::
    .string "…Unfortunately, you don't have\n"
    .string "space for this in your party.\p"
    .string "You'd better come back for it\n"
    .string "another time.$"

@ Unused
VermillionCity_PokemonFanClub_Text_YouveComeBackForTheEgg::
    .string "やあ\n"
    .string "タマゴを　もらいに\l"
    .string "きて　くれたんだね$"

VermillionCity_PokemonFanClub_Text_GladIMetSomeoneLikeYou::
    .string "I received that EGG when I was\n"
    .string "still sailing as a captain.\p"
    .string "I'm glad I met someone like you.$"

VermillionCity_PokemonFanClub_Text_CuteMonRemindsMeOfDaisy::
    .string "Oh, hello.\n"
    .string "That's a cute {STR_VAR_2}.\p"
    .string "Thank you for raising it so well!$"


