SevenIsland_TanobyRuins_Text_BrandonIntro::
    .string "Do you know anything about this\n"
    .string "stone chamber?$"

SevenIsland_TanobyRuins_Text_BrandonDefeat::
    .string "That was uncalled for.\n"
    .string "You didn't have to be so rough.$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
    .string "The TANOBY RUINS date back at\n"
    .string "least 1,500 years.\p"
    .string "But it's a baffling mystery as to\n"
    .string "why it was built in the first place.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro::
    .string "A mystic POKéMON is said to sleep\n"
    .string "inside here.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
    .string "I'm not much good in battle.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
    .string "I hear there are other ruins like\n"
    .string "the one here.\p"
    .string "Might they be the resting places\n"
    .string "of other mystic POKéMON?$"

SevenIsland_TanobyRuins_Text_EdnaIntro::
    .string "CLIFFORD is teaching me how to\n"
    .string "paint.$"

SevenIsland_TanobyRuins_Text_EdnaDefeat::
    .string "We might get in trouble for being\n"
    .string "noisy here.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
    .string "I said that I wanted to paint an\n"
    .string "old building.\p"
    .string "So CLIFFORD brought me here.$"

SevenIsland_TanobyRuins_Text_CliffordIntro::
    .string "Today, in addition to our lesson,\n"
    .string "we came to see the chamber.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat::
    .string "My, how extraordinary.$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
    .string "Ah, so you are studying POKéMON\n"
    .string "on your own…\p"
    .string "Yes, you certainly are quite the\n"
    .string "extraordinary person, indeed.$"

SevenIsland_TanobyRuins_Text_CynthiaIntro::
    .string "What's this? What an uncanny\n"
    .string "TRAINER resemblance... It's\p"
    .string "surprising to meet another one who\n"
    .string "has intense eyes like that POKéMON\p"
    .string "TRAINER. What's your name?\n"
    .string "... OK.\p"
    .string "{PLAYER}, nice to meet\n"
    .string "you. I'm CYNTHIA, another POKéMON\p"
    .string "TRAINER. I have an insatiable\n"
    .string "curiosity for learning about\p"
    .string "POKéMON myths. Lets see if you're\n"
    .string "worthy of facing legends!$"

SevenIsland_TanobyRuins_Text_CynthiaDefeat::
    .string "... Not bad.$"

SevenIsland_TanobyRuins_Text_CynthiaPostBattle::
    .string "That was beyond my expectations!\n"
    .string "What an exceptional battle! You\p"
    .string "certainly bear a resemblance to a\p"
    .string "TRAINER who himself faced POKéMON\n"
    .string "of myth and legend.\p"
    .string "... Oh, pardon me.\n"
    .string "I was just thinking out loud.$"

SevenIsland_TanobyRuins_Text_CynthiaWantsToGiveGible::
    .string "You're a great TRAINER, and it\n"
    .string "would make me happy to see you\l"
    .string "again sometime.\p"
    .string "I want you to have this POKéMON\n"
    .string "so you can grow further still.$"

SevenIsland_TanobyRuins_Text_ObtainedGibleFromCynthia::
    .string "{PLAYER} obtained a GIBLE from\n"
    .string "CYNTHIA!$"

SevenIsland_TanobyRuins_Text_ExplainGible::
    .string "It's a GIBLE. GIBLE are incredible!\n"
    .string "They're my favourite POKéMON.$"

SevenIsland_TanobyRuins_Text_NotNow::
    .string "I would like to enjoy the waves\n"
    .string "for the time being.$"





