VictoryRoad_2F_Text_DawsonIntro::
    .string "If you can get through here,\n"
    .string "you can go meet the ELITE FOUR.$"

VictoryRoad_2F_Text_DawsonDefeat::
    .string "No!\n"
    .string "Unbelievable!$"

VictoryRoad_2F_Text_DawsonPostBattle::
    .string "I can beat you when it comes to\n"
    .string "knowledge about POKéMON!$"

VictoryRoad_2F_Text_DaisukeIntro::
    .string "This here is VICTORY ROAD.\n"
    .string "It's the final test for TRAINERS!$"

VictoryRoad_2F_Text_DaisukeDefeat::
    .string "Atcho!$"

VictoryRoad_2F_Text_DaisukePostBattle::
    .string "If you get stuck, try moving some\n"
    .string "boulders around.$"

VictoryRoad_2F_Text_AaronIntro::
    .string "This little boy does not want to\n"
    .string "trade me his POKéMON!$"

VictoryRoad_2F_Text_AaronDefeat::
    .string "OH NO! MY DEAR BUGS!$"

VictoryRoad_2F_Text_AaronPostBattle::
    .string "Why did you have to come and ruin\n"
    .string "my trade talks.$"

VictoryRoad_2F_Text_TakeshiIntro::
    .string "This weird man wants me to give him\n"
    .string "my highly skilled Ninja-POKéMON!$"

VictoryRoad_2F_Text_TakeshiDefeat::
    .string "Hmph!$"

VictoryRoad_2F_Text_TakeshiPostBattle::
    .string "I hope this guy will finally stop\n"
    .string "bugging me now.$"

VictoryRoad_2F_Text_NelsonIntro::
    .string "Ah, so you wish to challenge the\n"
    .string "ELITE FOUR?$"

VictoryRoad_2F_Text_NelsonDefeat::
    .string "You got me!$"

VictoryRoad_2F_Text_NelsonPostBattle::
    .string "{RIVAL} also came through here.$"

VictoryRoad_2F_Text_VincentIntro::
    .string "Come on!\n"
    .string "I'll whip you!$"

VictoryRoad_2F_Text_VincentDefeat::
    .string "I got whipped!$"

VictoryRoad_2F_Text_VincentPostBattle::
    .string "You earned the right to be on\n"
    .string "VICTORY ROAD…$"

VictoryRoad_2F_Text_GregoryIntro::
    .string "Is VICTORY ROAD too tough?$"

VictoryRoad_2F_Text_GregoryDefeat::
    .string "Well done!$"

VictoryRoad_2F_Text_GregoryPostBattle::
    .string "Many TRAINERS give up their\n"
    .string "challenge here and go home.$"

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo::
    .string "ギヤーオ！$"

