FiveIsland_ResortGorgeous_Text_DaisyIntro::
    .string "With these hands, I will create\n"
    .string "my victory!$"

FiveIsland_ResortGorgeous_Text_DaisyDefeat::
    .string "The shame of this…\n"
    .string "I'm red-faced…$"

FiveIsland_ResortGorgeous_Text_DaisyPostBattle::
    .string "Uh-oh, my paint tubes have\n"
    .string "scattered everywhere!$"

FiveIsland_ResortGorgeous_Text_CelinaIntro::
    .string "Excuse me!\n"
    .string "I'm trying to paint.\l"
    .string "Please keep out of my sight!$"

FiveIsland_ResortGorgeous_Text_CelinaDefeat::
    .string "This loss…\n"
    .string "I feel like I'm whiting out…$"

FiveIsland_ResortGorgeous_Text_CelinaPostBattle::
    .string "GILLIAN?\n"
    .string "Please tilt your head slightly…\l"
    .string "There! That's the look I want!$"

FiveIsland_ResortGorgeous_Text_RaynaIntro::
    .string "Hmm…\n"
    .string "The angle, it is not quite there…$"

FiveIsland_ResortGorgeous_Text_RaynaDefeat::
    .string "Oh…\n"
    .string "My feelings, they are blue…$"

FiveIsland_ResortGorgeous_Text_RaynaPostBattle::
    .string "The sky and the sea…\n"
    .string "They are so fickle.\p"
    .string "Their changing expressions make\n"
    .string "them difficult to capture.$"

FiveIsland_ResortGorgeous_Text_JackiIntro::
    .string "I am visiting my friend's retreat,\n"
    .string "if you must know.$"

FiveIsland_ResortGorgeous_Text_JackiDefeat::
    .string "Oh, my, so strong.$"

FiveIsland_ResortGorgeous_Text_JackiPostBattle::
    .string "I find it pleasurable to leisurely\n"
    .string "battle in the gentle sea breeze.$"

FiveIsland_ResortGorgeous_Text_GillianIntro::
    .string "I'm thinking of having a pool\n"
    .string "made specially for POKéMON.$"

FiveIsland_ResortGorgeous_Text_GillianDefeat::
    .string "Oh, my goodness gracious!$"

FiveIsland_ResortGorgeous_Text_GillianPostBattle::
    .string "A pool would be nice, but I must\n"
    .string "say, a sun-room may be sublime.$"

FiveIsland_ResortGorgeous_Text_DestinIntro::
    .string "I'm a good runner.\n"
    .string "I'm really fast!$"

FiveIsland_ResortGorgeous_Text_DestinDefeat::
    .string "Oops!\n"
    .string "I rushed things!$"

FiveIsland_ResortGorgeous_Text_DestinPostBattle::
    .string "When I run with the wind, it feels\n"
    .string "like I could fly!$"

FiveIsland_ResortGorgeous_Text_TobyIntro::
    .string "I say, this marine life here at\n"
    .string "this resort agrees with me.$"

FiveIsland_ResortGorgeous_Text_TobyDefeat::
    .string "That's a shocker!\n"
    .string "You must be joking.$"

FiveIsland_ResortGorgeous_Text_TobyPostBattle::
    .string "Getting so serious over this…\n"
    .string "How nonsensical.$"

FiveIsland_ResortGorgeous_Text_SelphyThanksYouMayGoNow::
    .string "SELPHY: Thank you.\p"
    .string "You may go now.$"

FiveIsland_ResortGorgeous_Text_SelphysHouse::
    .string "SELPHY'S HOUSE$"

FiveIsland_ResortGorgeous_Text_CynthiaIntro::
    .string "What's this? What an uncanny\n"
    .string "TRAINER resemblance... It's\p"
    .string "surprising to meet another one who\n"
    .string "has intense eyes like that POKéMON\p"
    .string "TRAINER. What's your name?\n"
    .string "... OK.\p"
    .string "{PLAYER}, nice to meet\n"
    .string "you. I'm CYNTHIA, another POKéMON\p"
    .string "TRAINER. I have an insatiable\n"
    .string "curiosity for learning about\p"
    .string "POKéMON myths. Lets see if you're\n"
    .string "worthy of facing legends!$"

FiveIsland_ResortGorgeous_Text_CynthiaDefeat::
    .string "...$"

FiveIsland_ResortGorgeous_Text_CynthiaPostBattle::
    .string "That was beyond my expectations!\n"
    .string "What an exceptional battle! You\p"
    .string "certainly bear a resemblance to a\p"
    .string "TRAINER who himself faced POKéMON\n"
    .string "of myth and legend.\p"
    .string "... Oh, pardon me..\n"
    .string "I was just thinking out loud. I\n"
    .string "love being on holiday here. But\n"
    .string "the calm makes my mind wander!$"

FiveIsland_ResortGorgeous_Text_CynthiaWantsToGiveGible::
    .string "You're a great TRAINER, and it\n"
    .string "would make me happy to see you\l"
    .string "again sometime.\p"
    .string "I want you to have this POKéMON\n"
    .string "so you can grow further still.$"

FiveIsland_ResortGorgeous_Text_ObtainedGibleFromCynthia::
    .string "{PLAYER} obtained a GIBLE from\n"
    .string "CYNTHIA!$"

FiveIsland_ResortGorgeous_Text_ExplainGible::
    .string "It's a GIBLE. GIBLE are incredible!\n"
    .string "They're my favourite POKéMON.$"

FiveIsland_ResortGorgeous_Text_NotNow::
    .string "I would like to enjoy the waves\n"
    .string "for the time being.$"

