CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
    .string "REPEL not only keeps bugs away,\n"
    .string "it also works on weak POKéMON.\p"
    .string "Put your strongest POKéMON at the\n"
    .string "left of the POKéMON LIST.\p"
    .string "If your first POKéMON is strong,\n"
    .string "REPEL's effect is boosted.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
    .string "Do you know about RARE CANDY?\n"
    .string "They don't sell it in shops.\p"
    .string "I think it makes POKéMON grow\n"
    .string "very quickly all of a sudden.$"

CeruleanCity_Mart_Text_HaveMonForBeingATrainer::
    .string "Oh! Hi! You're also a TRAINER!\n"
    .string "Are you here to improve yourself?\l"
    .string "I remember once being like you.\p"
    .string "Please accept this POKéMON.$"

CeruleanCity_Mart_Text_ObtainedVanilliteFromOldTrainer::
    .string "{PLAYER} obtained a VANILLITE from\n"
    .string "the retired TRAINER!$"

CeruleanCity_Mart_Text_ExplainVanillite::
    .string "It's a VANILLLITE.\n"
    .string "It's a POKéMON with a lot of \p"
    .string "potential. Train it well! And you\n"
    .string "will unleash the power it can hold\n"
    .string "I think you will be a good TRAINER\n"
    .string "for VANILLITE!$"

