SixIsland_PatternBush_Text_BethanyIntro::
    .string "I'm curious, how do you raise your\n"
    .string "POKéMON?$"

SixIsland_PatternBush_Text_BethanyDefeat::
    .string "You raise your POKéMON with a\n"
    .string "whole lot of love!$"

SixIsland_PatternBush_Text_BethanyPostBattle::
    .string "In the same way your mother raised\n"
    .string "you full of love, you should raise\l"
    .string "your POKéMON.$"

SixIsland_PatternBush_Text_AllisonIntro::
    .string "I'm working to preserve the natural\n"
    .string "ecology of POKéMON here.$"

SixIsland_PatternBush_Text_AllisonDefeat::
    .string "Oh, for someone so young, you are\n"
    .string "tremendous!$"

SixIsland_PatternBush_Text_AllisonPostBattle::
    .string "I'm not saying that you shouldn't\n"
    .string "catch POKéMON.\p"
    .string "I just want people to raise their\n"
    .string "POKéMON responsibly.$"

SixIsland_PatternBush_Text_AlderIntro::
    .string "My name is Alder! I'm a TRAINER with\n"
    .string "a keen interest in the world. One of\p"
    .string "my goals is to tell people about how\n"
    .string "wonderful it is to walk toward the\p"
    .string "future together with POKéMON\n"
    .string "Say now, how about a match with the\p"
    .string "strongest TRAINER around here?$"

SixIsland_PatternBush_Text_AlderDefeat::
    .string "After the battle, a fresh wind blew\n" 
    .string "through my heart... Use the battle\p"
    .string "with me as a stepping stone and move\n"
    .string "forward!$"

SixIsland_PatternBush_Text_AlderPostBattle::
    .string "That was beyond my expectations!\n"
    .string "What an exceptional battle! Well\p"
    .string "done!$"

SixIsland_PatternBush_Text_AlderWantsToGiveLarvesta::
    .string "Well done! You certainly are an\n" 
    .string "unmatched talent! Take this!$"

SixIsland_PatternBush_Text_ObtainedLarvestaFromAlder::
    .string "{PLAYER} obtained LARVESTA from\n"
    .string "ALDER!$"

SixIsland_PatternBush_Text_ExplainLarvesta::
    .string "It's a LARVESTA. Their power equals\n"
    .string "that of the sun.$"

SixIsland_PatternBush_Text_NotNow::
    .string "I will explore some more around\n"
    .string "here.$"

SixIsland_PatternBush_Text_JonahIntro::
    .string "You know, it just doesn't feel right\n"
    .string "if I don't use BUG POKéMON.$"

SixIsland_PatternBush_Text_JonahDefeat::
    .string "It's okay, losing is a fun part of\n"
    .string "POKéMON's appeal, too.$"

SixIsland_PatternBush_Text_JonahPostBattle::
    .string "By the way, “appeal” is a weird\n"
    .string "word, if you think about it.\p"
    .string "Like, is it like an orange peel?\n"
    .string "Or like a ringing bell?$"

SixIsland_PatternBush_Text_VanceIntro::
    .string "I caught a BUG POKéMON that lives\n"
    .string "only around here!$"

SixIsland_PatternBush_Text_VanceDefeat::
    .string "Heheh…\n"
    .string "Isn't my POKéMON awesome?$"

SixIsland_PatternBush_Text_VancePostBattle::
    .string "There's a girl near the BUSH who\n"
    .string "measures HERACROSS for TRAINERS.$"

SixIsland_PatternBush_Text_NashIntro::
    .string "Look, look! There are funny\n"
    .string "patterns on the ground.$"

SixIsland_PatternBush_Text_NashDefeat::
    .string "Super awesome!$"

SixIsland_PatternBush_Text_NashPostBattle::
    .string "The funny patterns on the ground…\p"
    .string "They look like the patterns on my\n"
    .string "grandpa's clothes.$"

SixIsland_PatternBush_Text_CordellIntro::
    .string "I bet you think I'm just some guy,\n"
    .string "don't you, eh?$"

SixIsland_PatternBush_Text_CordellDefeat::
    .string "I bet you think I'm weak,\n"
    .string "don't you, eh?$"

SixIsland_PatternBush_Text_CordellPostBattle::
    .string "Ayup, you townies come around all\n"
    .string "so dandy with a hat that flashy…\p"
    .string "How about giving me that?$"

SixIsland_PatternBush_Text_DaliaIntro::
    .string "Take a deep breath.\n"
    .string "Isn't the air delicious?$"

SixIsland_PatternBush_Text_DaliaDefeat::
    .string "If you'd like, I can teach you how\n"
    .string "to breathe properly.$"

SixIsland_PatternBush_Text_DaliaPostBattle::
    .string "First, exhale.\n"
    .string "Blow everything out.\p"
    .string "When you can't exhale anymore,\n"
    .string "inhale the clean air!\p"
    .string "Isn't it refreshing?$"

SixIsland_PatternBush_Text_JoanaIntro::
    .string "I love BUG POKéMON.\n"
    .string "That's why I'm here all the time.\p"
    .string "Am I the only girl like that?$"

SixIsland_PatternBush_Text_JoanaDefeat::
    .string "I lost, but I'm still laughing.\n"
    .string "Am I the only girl like that?$"

SixIsland_PatternBush_Text_JoanaPostBattle::
    .string "I'm going to keep on collecting\n"
    .string "BUG POKéMON.\p"
    .string "Am I the only girl like that?$"

SixIsland_PatternBush_Text_RileyIntro::
    .string "This is a good spot.\n"
    .string "I'll pitch my tent here.$"

SixIsland_PatternBush_Text_RileyDefeat::
    .string "Wimped out…$"

SixIsland_PatternBush_Text_RileyPostBattle::
    .string "I'm going to observe the night sky\n"
    .string "here.$"

SixIsland_PatternBush_Text_MarcyIntro::
    .string "Oh, yuck!\n"
    .string "I think a bug stung me!$"

SixIsland_PatternBush_Text_MarcyDefeat::
    .string "It wasn't a bug.\n"
    .string "I cut my shin on some grass.$"

SixIsland_PatternBush_Text_MarcyPostBattle::
    .string "A little cut like that…\n"
    .string "A little spit's enough to cure it!$"

SixIsland_PatternBush_Text_LaytonIntro::
    .string "Have you noticed something odd\n"
    .string "about these parts?$"

SixIsland_PatternBush_Text_LaytonDefeat::
    .string "Have you taken a good look around\n"
    .string "your feet?$"

SixIsland_PatternBush_Text_LaytonPostBattle::
    .string "There are places here in PATTERN\n"
    .string "BUSH where grass won't grow.\p"
    .string "What could be the cause of such\n"
    .string "a phenomenon?$"

